version: "2"
services:
  db:
    environment:
      - MYSQL_DATABASE=wordpressdb
      - MYSQL_PASSWORD=123sqwert
      - MYSQL_ROOT_PASSWORD=123sqwert
      - MYSQL_USER=admin
    image: 'mariadb:latest'
    container_name: wordpress_db
    ports:
      - '3306:3306'
    volumes:
      - '/var/www/db:/var/www/db'

  web:    
    ports:
      - '80:80'
    image: 'wordpress:php7.1'
    container_name: wordpress_web
    links:
      - db
    volumes:
      - '/var/www/html:/var/www/html'

